Feature/843 sommar hus list updateadd function
sandrasofiaa/Grupparbete-Api pull request #89
Opened 2024-01-25 00:22 UTC by Levy70

2024-01-26 07:18 UTC, sandrasofiaa requested changes
Du har ändrat i AddFamilyDto:n, finns det någon funktionalitet kring detta? Annars ta bort required från denna :)

2024-01-26 12:28 UTC, sandrasofiaa requested changes
Det är i AddNewFamilyDto som du behöver ändra tillbaka. Inte i updatedto:n :)

2024-01-26 14:30 UTC, sandrasofiaa approved these changes

2024-01-27 23:28 UTC, Mohammadahm96 approved these changes

2024-01-27 23:28 UTC, merged